os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng build --prod

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: "330manage"