language: node_js

node_js:
  - "6.10"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng test --watch false
  - ng e2e