os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
install:
  - npm install
script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive